language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r kdu-chatbot-service *
  - mkdir -p deploy
  - mv kdu-chatbot-service.zip deploy/kdu-chatbot-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis Environment Variables
    secret_access_key: $AWS_SECRET_KEY # Travis Environment Variables
    bucket: kdu-chatbot-service-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    on:
      repo: hyojaekim/chatbot #Github 주소
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hyojaedev@gmail.com